=== elbonian/promethean.ai/JSON_input/Schemas/Init_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Init",
    "definitions": {
        "Init": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "initial_state": {
                    "type": "object",
                    "items": {
                        "$ref": "../InitState_schema.json#/InitState"
                    }
                },
                "goal_state": {
                    "type": "object",
                    "items": {
                        "$ref": "../GoalState_schema.json#/GoalState"
                    }
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "../Task_schema.json#/Task"
                    }
                },
                 "optimizations": {
                    "type": "array",
                    "items": {
                        "$ref": "../Optimization_schema.json#/Optimization"
                    }
                },
                "perturbations": {
                    "type": "array",
                    "items": {
                        "$ref": "../Perturbation_schema.json#/Perturbation"
                    }
                }
            },
            "required": [
                "initial_state",
                "goal_state",
                "tasks"
            ],
            "title": "Init"
        }
    }
}

=== elbonian/promethean.ai/JSON_input/TestCases/many_paths.json
{
  "initial_state": {
    "properties": [
      {"name": "battery", "value": 100.0},
      {"name": "solarPanelsOpen", "value": false},
      {"name": "isHappy", "value": false},
      {"name": "altitude", "value": 70.0},
      {"name": "doorOpen", "value": false},
      {"name": "dataCollected", "value": 0.0}
    ]
  },
  "goal_state": {
    "requirements": [
      {"name": "battery", "value": 80.0, "operator": ">="},
      {"name": "solarPanelsOpen", "value": true, "operator": "=="},
      {"name": "isHappy", "value": true, "operator": "=="},
      {"name": "altitude", "value": 120.0, "operator": "=="},
      {"name": "dataCollected", "value": 75.0, "operator": ">="},
      {"name": "doorOpen", "value": false, "operator": "=="}
    ]
  },
  "tasks": [
    {
      "name": "openSolarPanels",
      "duration": 5,
      "requirements": [
        {"name": "solarPanelsOpen", "value": false, "operator": "=="},
        {"name": "battery", "value": 10.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "battery", "type": "delta", "value": -10.0},
        {"name": "solarPanelsOpen", "type": "assignment", "value": true}
      ]
    },
    {
      "name": "closeSolarPanels",
      "duration": 5,
      "requirements": [
        {"name": "solarPanelsOpen", "value": true, "operator": "=="},
        {"name": "battery", "value": 20.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "solarPanelsOpen", "type": "assignment", "value": false},
        {"name": "battery", "type": "delta", "value": -10.0}
      ]
    },
    {
      "name": "chargeBattery",
      "duration": 10,
      "requirements": [
        {"name": "solarPanelsOpen", "value": true, "operator": "=="},
        {"name": "battery", "value": 100.0, "operator": "<"}
      ],
      "property_impacts": [
        {"name": "battery", "type": "delta", "value": 20.0}
      ]
    },
    {
      "name": "makeHappy",
      "duration": 15,
      "requirements": [
        {"name": "isHappy", "value": false, "operator": "=="},
        {"name": "battery", "value": 25, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "isHappy", "type": "assignment", "value": true},
        {"name": "battery", "type": "delta", "value": -20.0}
      ]
    },
    {
      "name": "raiseAltitude10",
      "duration": 20,
      "requirements": [
        {"name": "altitude", "value": 0.0, "operator": ">"},
        {"name": "battery", "value": 25.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "altitude", "type": "delta", "value": 10.0},
        {"name": "battery", "type": "delta", "value": -10.0}
      ]
    },
    {
      "name": "openDoor",
      "duration": 5,
      "requirements": [
        {"name": "doorOpen", "value": false, "operator": "=="},
        {"name": "battery", "value": 15.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "doorOpen", "type": "assignment", "value": true},
        {"name": "battery", "type": "delta", "value": -5.0}
      ]
    },
    {
      "name": "closeDoor",
      "duration": 5,
      "requirements": [
        {"name": "doorOpen", "value": true, "operator": "=="},
        {"name": "battery", "value": 15.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "doorOpen", "type": "assignment", "value": false},
        {"name": "battery", "type": "delta", "value": -5.0}
      ]
    },
    {
      "name": "collectData",
      "duration": 15,
      "requirements": [
        {"name": "doorOpen", "value": true, "operator": "=="},
        {"name": "altitiude", "value": 100.0, "operator": ">="},
        {"name": "battery", "value": 50.0, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "dataCollected", "type": "delta", "value": 15.0},
        {"name": "isHappy", "type": "assignment", "value": false},
        {"name": "battery", "type": "delta", "value": -5.0}
      ]
    }
  ],
  "optimizations": [
    {
      "name": "battery",
      "weight": 0,
      "type": "max"
    }
  ],
  "perturbations": [

  ]
}

=== elbonian/promethean.ai/JSON_input/InputFiles/PerturbationTest.json
{
  "initial_state": {
    "properties": [
      {"name": "speed", "value": 0.0},
      {"name": "doorOpen", "value": false},
      {"name": "Fuel","value":100.0},
      {"name": "wheelHealth", "value":100.0},
      {"name": "wheelsDown", "value": false},
      {"name": "Altitude", "value": 0.0}
    ]
  },
  "goal_state": {
    "requirements": [
      {"name": "wheelsDown", "value": true, "operator": "=="},
      {"name": "doorOpen", "value": true, "operator": "=="},
      {"name": "Altitude", "value": 0.000001, "operator": ">="}
    ]
  },
  "tasks": [
    {
      "name" : "Open Door",
      "duration": 20,
      "requirements":[
        {"name": "Fuel","value":60.0, "operator": ">"},
        {"name": "Altitude", "value":0.0, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "doorOpen", "type": "assignment","value": true},
        {"name": "Fuel","type": "delta", "value":-10.0}
      ]
    },
    {
      "name" : "Wheels Down",
      "duration": 30,
      "requirements":[
        {"name": "Fuel","value":60.0, "operator": ">"},
        {"name": "Altitude", "value":0.0, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "wheelsDown", "type": "assignment","value": true},
        {"name": "Fuel","type": "delta", "value":-10.0}

      ]
    },
    {
      "name" : "Altitude",
      "duration": 10,
      "requirements":[
        {"name": "Fuel","value":60.0, "operator": ">"}
      ],
      "property_impacts": [
        {"name": "Altitude", "type": "delta","value": 0.000001},
        {"name": "Fuel","type": "delta", "value":-10.0}

      ]
    },
    {
      "name" : "AltitudeMinus",
      "duration": 10,
      "requirements":[
        {"name": "Fuel","value":60.0, "operator": ">"}
      ],
      "property_impacts": [
        {"name": "Altitude", "type": "delta","value": -0.000001},
        {"name": "Fuel","type": "delta", "value":-10.0}

      ]
    }
  ],
  "optimizations": [
    {
      "name": "Fuel",
      "weight": 0.54,
      "type": "maximization"
    }
  ],
  "perturbations": [
    {
      "name": "WillNeverHappen",
      "time": 3000,
      "property_impacts": [{"name": "speed","type": "delta","value": 1}]
    },
    {
      "name": "Acceleration",
      "time": 10,
      "property_impacts": [{"name": "speed","type": "delta","value": 1}]
    },
    {
      "name": "delay",
      "time": 15,
      "property_impacts": [{"name":  "time","type": "delta","value": 10}]
    }
  ]
}

=== elbonian/promethean.ai/JSON_input/TestCases/mission_to_mars.json
{
  "initial_state": {
    "properties": [
      {"name": "agent", "value": "rocket"},
      {"name": "location", "value": "Earth"},
      {"name": "speed", "value": 0},
      {"name": "battery", "value": 0},
      {"name": "rocketFuel", "value": 100},
      {"name": "boosterFuel", "value": 100},
      {"name": "solarPanelsExtended", "value": false},
      {"name": "landingGearExtended", "value": false},
      {"name": "parachuteAttached", "value": true},
      {"name": "seismometerAttached", "value": true},
      {"name": "coverAttached", "value": true},
      {"name": "heatProbeAttached", "value": true}
    ]
  },
  "goal_state": {
    "requirements": [
      {"name": "agent", "value": "lander", "operator": "=="},
      {"name": "location", "value": "Mars ground", "operator": "=="},
      {"name": "speed", "value": 0, "operator": "=="},
      {"name": "solarPanelsExtended", "value": true, "operator": "=="},
      {"name": "landingGearExtended", "value": true, "operator": "=="},
      {"name": "parachuteAttached", "value": false, "operator": "=="},
      {"name": "seismometerAttached", "value": false, "operator": "=="},
      {"name": "coverAttached", "value": false, "operator": "=="},
      {"name": "heatProbeAttached", "value": false, "operator": "=="}
    ]
  },
  "tasks": [
    {
      "name": "charge_battery",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "solarPanelsExtended", "value": true, "operator": "=="},
        {"name": "battery", "value": 90, "operator": "<="}
      ],
      "property_impacts": [
        {"name": "battery", "value": 10, "type": "delta"}
      ]
    },
    {
      "name": "extend_solar_panels",
      "duration": 1,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "solarPanelsExtended", "value": false, "operator": "=="},
        {"name": "speed", "value": 0, "operator": "=="},
        {"name": "location", "value": "Mars ground", "operator": "=="}
      ],
      "property_impacts": [
        {"name": "solarPanelsExtended", "value": true}
      ]
    },
    {
      "name": "accelerate_rocket",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "rocket", "operator": "=="},
        {"name": "rocketFuel", "value": 10, "operator": ">="}
      ],
      "property_impacts": [
        {"name": "speed", "value": 1000, "type": "delta"},
        {"name": "rocketFuel", "value": -10, "type": "delta"}
      ]
    },
    {
      "name": "drop_boosters",
      "duration": 1,
      "requirements": [
        {"name": "location", "value": "Earth", "operator": "=="},
        {"name": "speed", "value": 10000, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "location", "value": "interplanetary space"},
        {"name": "rocketFuel", "value": 0},
        {"name": "agent", "value": "cruise stage"}
      ]
    },
    {
      "name": "cruise",
      "duration": 280800,
      "requirements": [
        {"name": "agent", "value": "cruise stage", "operator": "=="},
        {"name": "location", "value": "interplanetary space", "operator": "=="}
      ],
      "property_impacts": [
        {"name": "agent", "value": "landing capsule"},
        {"name": "location", "value": "Mars atmosphere"}
      ]
    },
    {
      "name": "decelerate_with_parachute",
      "duration": 5,
      "requirements": [
        {"name": "agent", "value": "landing capsule", "operator": "=="},
        {"name": "location", "value": "Mars atmosphere", "operator": "=="},
        {"name": "parachuteAttached", "value": true, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "parachuteAttached", "value": false},
        {"name": "speed", "value": -9000, "type": "delta"},
        {"name": "agent", "value": "lander"}
      ]
    },
    {
      "name": "extend_landing_gear",
      "duration": 1,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "speed", "value": 0, "operator": ">"},
        {"name": "landingGearExtended", "value": false, "operator": "=="},
        {"name": "location", "value": "Mars atmosphere", "operator": "=="}
      ],
      "property_impacts": [
        {"name": "landingGearExtended", "value": true}
      ]
    },
    {
      "name": "decelerate_with_thrusters",
      "duration": 2,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "speed", "value": 0, "operator": ">"},
        {"name": "boosterFuel", "value": 0, "operator": ">"},
        {"name": "location", "value": "Mars atmosphere", "operator": "=="}
      ],
      "property_impacts": [
        {"name": "speed", "value": -100, "type": "delta"},
        {"name": "boosterFuel", "value": -10, "type": "delta"}
      ]
    },
    {
      "name": "land",
      "duration": 1,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "speed", "value": 0, "operator": "=="},
        {"name": "landingGearExtended", "value": true, "operator": "=="},
        {"name": "location", "value": "Mars atmosphere", "operator": "=="}
      ],
      "property_impacts": [
        {"name": "location", "value": "Mars ground"}
      ]
    },
    {
      "name": "charge_battery",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "battery", "value": 100, "operator": "<"},
        {"name": "solarPanelsExtended", "value": true, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "battery", "value": 10, "type": "delta"}
      ]
    },
    {
      "name": "place_seismometer",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "battery", "value": 10, "operator": ">="},
        {"name": "seismometerAttached", "value": true, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "battery", "value": -10, "type": "delta"},
        {"name": "seismometerAttached", "value": false}
      ]
    },
    {
      "name": "place_heat_probe",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "battery", "value": 10, "operator": ">="},
        {"name": "heatProbeAttached", "value": true, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "battery", "value": -10, "type": "delta"},
        {"name": "heatProbeAttached", "value": false}
      ]
    },
    {
      "name": "place_seismometer_cover",
      "duration": 10,
      "requirements": [
        {"name": "agent", "value": "lander", "operator": "=="},
        {"name": "battery", "value": 10, "operator": ">="},
        {"name": "coverAttached", "value": true, "operator": "=="},
        {"name": "seismometerAttached", "value": false, "operator": "=="}
      ],
      "property_impacts": [
        {"name": "battery", "value": -10, "type": "delta"},
        {"name": "coverAttached", "value": false}
      ]
    }
  ],
  "optimizations": [
    {
      "name": "time",
      "weight": 1,
      "type": "min"
    },
    {
      "name": "rocketFuel",
      "weight": 1,
      "type": "max"
    },
    {
      "name": "boosterFuel",
      "weight": 1,
      "type": "max"
    }
  ],
  "perturbations": [

  ]
}
